"""Add image_url to events

Revision ID: 8998808a320e
Revises: edfd53f20f7f
Create Date: 2026-03-06 01:37:35.024587

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8998808a320e"
down_revision: str | Sequence[str] | None = "edfd53f20f7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "image_url")
    # ### end Alembic commands ###
